### ISSUE TITLE
希望可以在readme 文件里面增加使用方法

### ISSUE THREAD

**Issue by ymml7** [wzv5/rime-lua-script#1]
比如将lua文件放置在哪里, 需要进行什么操作(虽然lua文件开头有写但是终究不是很方便, 也不是很完整)
我目前的状况是把lua文件放到rime用户设定的文件夹里了, 并且更改了我使用的.schema.yaml文件, 但是并不能正确运行

**Comment by wzv5** [comment]
已添加安装方法。
